import { Col, Row } from "antd";
import Head from "next/head";
import Circular from "../components/dashboard/circularProgress";
import StatisticCard from "../components/dashboard/statistic";
import Navbar from "../components/navbar";
import ProgressBar from "../components/dashboard/progressBar";
import styles from "../styles/Home.module.scss";
import MtiCount from "../components/dashboard/mtiCount";

const DashBoard = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Logs Viewer</title>
        <meta name="description" content="Generated by Yusor" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar defaultSelectedKeys={"1"}>
        <main className={styles.main}>
          <Row>
            <MtiCount />
          </Row>
          <Row justify="space-between">
            <Col
              span={10}
              xs={{ order: 1 }}
              sm={{ order: 2 }}
              md={{ order: 3 }}
              lg={{ order: 4 }}
            >
              <ProgressBar />
            </Col>
          </Row>
          <hr style={{ margin: "100px" }} />
          <Row justify="space-between">
            <Col
              span={10}
              xs={{ order: 1 }}
              sm={{ order: 2 }}
              md={{ order: 3 }}
              lg={{ order: 4 }}
            >
              <Circular />
            </Col>
            <Col
              span={10}
              xs={{ order: 1 }}
              sm={{ order: 2 }}
              md={{ order: 3 }}
              lg={{ order: 4 }}
            >
              <StatisticCard />
            </Col>
          </Row>
        </main>
      </Navbar>
    </div>
  );
};
export default DashBoard;
