import Head from "next/head";
import Login from "../components/login";
import styles from "../styles/Home.module.scss";
import Log from "./log";

export default function Home() {
  var token = "";
  if (typeof window !== "undefined") {
    token = localStorage.getItem("token") ? "true" : "false";
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Logs Viewer</title>
        <meta name="description" content="Generated by Yusor" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {token === "true" ? <Log /> : <Login />}
    </div>
  );
}
