import React, { useState, useEffect } from "react";
import { Upload, Button, Alert } from "antd";
import { InboxOutlined } from "@ant-design/icons";
import styles from "../styles/Home.module.scss";
import Head from "next/head";
import Navbar from "../components/navbar";
import { Client } from "../api";

const { Dragger } = Upload;
const UploadLog = () => {
  const [antPics, setAntPics] = useState([]);

  const [display, setDisplay] = useState("false");
  const [done, setDone] = useState("true");
  const handleAnt = (e) => {
    setAntPics(e.file.originFileObj);
  };
  const uploadd = async () => {
    const formData = new FormData();
    formData.append("logFile", antPics);
    Client.post(`api/uploadLog`, formData)
      .then((response) => {
        setDone(response?.data.message);
        setDisplay("true");
      })
      .catch((error) => {
        setDone(error);
        setDisplay("true");
      });
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Logs Viewer</title>
        <meta name="description" content="Generated by Yusor" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar defaultSelectedKeys={"2"}>
        <main className={styles.main}>
          <div className={styles.upload}>
            <Dragger onChange={handleAnt}>
              <p className="ant-upload-drag-icon">
                <InboxOutlined />
              </p>
              <p className="ant-upload-text">
                Click or drag file to this area to upload
              </p>
              <p className="ant-upload-hint">
                Strictly prohibit from uploading company data or other band
                files
              </p>
            </Dragger>
            <Button type="primary" onClick={uploadd}>
              Upload File
            </Button>
          </div>
          {display == "true" && (
            <Alert message={done} type="success" closable="true" showIcon />
          )}
        </main>
      </Navbar>
    </div>
  );
};

export default UploadLog;
